### ISSUE TITLE
Atualizar README.md

### ISSUE THREAD

**Issue by elisboa** [jntoledo/terraform-module-vpc#1]
O README.md deve ser atualizado com:

* nome do projeto
* objetivo
* como utilizar (exemplos práticos)
* erros conhecidos (opcional)
* planos futuros (opcional)

Referências
1. https://github.com/RichardLitt/standard-readme#readme
2. https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
3. https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

**Comment by jntoledo** [comment]
Correções efetuadas.
